const DATA_PELICULAS = [
    {
        "titulo": "Una pelicula de Minecraft",
        "duracion": 101,
        "genero": "Accion, aventura, comedia",
        "actores": ["Jason Momoa", "Jack Black", "Emma Myers, Jennifer Coolidge"],
        "linkActores":["https://es.wikipedia.org/wiki/Jason_Momoa",
        "https://es.wikipedia.org/wiki/Jack_Black",
        "https://es.wikipedia.org/wiki/Emma_Myers",
        "https://es.wikipedia.org/wiki/Jennifer_Coolidge"],
        "descripcion": "¡Bienvenidos al mundo de Minecraft, donde la creatividad no solo te ayuda a crear, sino que es esencial para la supervivencia! Cuatro inadaptados Garrett “El Hombre de la Basura” Garrison (Momoa), Henry (Hansen), Natalie (Myers) y Dawn (Brooks)—se encuentran lidiando con problemas cotidianos cuando, de repente, son transportados a través de un misterioso portal al Overworld: un extraño país de maravillas cúbico que prospera con la imaginación. Para regresar a casa, deberán dominar este mundo (y protegerlo de cosas malvadas como los Piglins y los Zombies) mientras emprenden una mágica aventura con un inesperado y experto creador, Steve (Black). Juntos, su aventura los desafiará a ser valientes y reconectar con las cualidades que hacen que cada uno de ellos sea creativamente único… las mismas habilidades que necesitan para prosperar de nuevo en el mundo real.",
        "iframe": "https://www.youtube.com/embed/bwAbeOvpfq0?si=NlDesm10UiW4keQE",
        "portadaJPG": "https://m.media-amazon.com/images/M/MV5BMGJjMDZiNzYtOWNjNS00MmYwLTg4NjAtYTJmYjZmODBlMzYzXkEyXkFqcGc@._V1_FMjpg_UX1000_.jpg",
        "rating": 5.7,
        "clasificacion": "ATP",
        "estreno": 2025,
        "linkComenzar": "https://www.youtube.com/watch?v=bwAbeOvpfq0&t=2s"
    },  
        {
          "titulo": "El Padrino",
          "duracion": 175,
          "genero": "Drama, crimen, gánsteres",
          "actores": ["Marlon Brando", "Al Pacino", "James Caan", "Robert Duvall"],
          "linkActores": ["https://es.wikipedia.org/wiki/Marlon_Brando", "https://es.wikipedia.org/wiki/Al_Pacino", "https://es.wikipedia.org/wiki/James_Caan", "https://es.wikipedia.org/wiki/Robert_Duvall"],
          "descripcion": "La historia de la familia Corleone y la transformación de Michael Corleone en líder de la mafia.",
          "iframe": "https://www.youtube.com/embed/iOyQx7MXaz0?si=LS4qW6GgWWB1qI3v",
          "portadaJPG": "https://a.ltrbxd.com/resized/film-poster/5/1/8/1/8/51818-the-godfather-0-1000-0-1500-crop.jpg?v=bca8b67402",
          "rating": 9.2,
          "clasificacion": "+18",
          "estreno": 1972,
          "linkComenzar": "https://www.youtube.com/watch?v=iOyQx7MXaz0"
        },
        {
          "titulo": "The Batman",
          "duracion": 175,
          "genero": "Acción, misterio, superhéroes",
          "actores": ["Robert Pattinson", "Zoë Kravitz", "Paul Dano", "Colin Farrell"],
          "linkActores": ["https://es.wikipedia.org/wiki/Robert_Pattinson", "https://es.wikipedia.org/wiki/Zoë_Kravitz", "https://es.wikipedia.org/wiki/Paul_Dano", "https://es.wikipedia.org/wiki/Colin_Farrell"],
          "descripcion": "Batman investiga una trama de corrupción en Gotham mientras persigue al Acertijo.",
          "iframe": "https://www.youtube.com/embed/fWQrd6cwJ0A?si=YpkHtTT7CE_riWB0",
          "portadaJPG": "https://a.ltrbxd.com/resized/film-poster/3/4/8/9/1/4/348914-the-batman-0-2000-0-3000-crop.jpg?v=ec12a8b7ce",
          "rating": 8.5,
          "clasificacion": "+13",
          "estreno": 2022,
          "linkComenzar": ""
        },
        {
          "titulo": "Midsommar",
          "duracion": 147,
          "genero": "Terror, drama, misterio",
          "actores": ["Florence Pugh", "Jack Reynor", "William Jackson Harper"],
          "linkActores": ["https://es.wikipedia.org/wiki/Florence_Pugh", "https://es.wikipedia.org/wiki/Jack_Reynor", "https://es.wikipedia.org/wiki/William_Jackson_Harper"],
          "descripcion": "Una pareja viaja a Suecia y se ve atrapada en un extraño y violento festival de verano.",
          "iframe": "https://www.youtube.com/embed/fcylOJ0twFw?si=5HBzaSvfUY9IRHKs",
          "portadaJPG": "https://a.ltrbxd.com/resized/film-poster/4/5/9/5/6/4/459564-midsommar-0-2000-0-3000-crop.jpg?v=ed7b8ded1f",
          "rating": 7.1,
          "clasificacion": "+16",
          "estreno": 2019,
          "linkComenzar": "https://www.youtube.com/watch?v=fcylOJ0twFw"
        },
        {
          "titulo": "El cisne negro",
          "duracion": 108,
          "genero": "Drama, thriller psicológico",
          "actores": ["Natalie Portman", "Mila Kunis", "Vincent Cassel"],
          "linkActores": ["https://es.wikipedia.org/wiki/Natalie_Portman", "https://es.wikipedia.org/wiki/Mila_Kunis", "https://es.wikipedia.org/wiki/Vincent_Cassel"],
          "descripcion": "Una bailarina de ballet obsesionada con la perfección enfrenta su lado oscuro.",
          "iframe": "https://www.youtube.com/embed/5jaI1XOB-bs?si=9ESRtA06TfpoJtDp",
          "portadaJPG": "https://a.ltrbxd.com/resized/sm/upload/yt/ae/iz/kj/bIjkE9Og0nulRycj144sCcQcsZ6-0-1000-0-1500-crop.jpg?v=a571e4c644",
          "rating": 8.0,
          "clasificacion": "+16",
          "estreno": 2010,
          "linkComenzar": "https://www.youtube.com/watch?v=5jaI1XOB-bs"
        },
        {
          "titulo": "Inception",
          "duracion": 148,
          "genero": "Ciencia ficción, acción, thriller",
          "actores": ["Leonardo DiCaprio", "Joseph Gordon-Levitt", "Elliot Page", "Tom Hardy"],
          "linkActores": ["https://es.wikipedia.org/wiki/Leonardo_DiCaprio", "https://es.wikipedia.org/wiki/Joseph_Gordon-Levitt", "https://es.wikipedia.org/wiki/Elliot_Page", "https://es.wikipedia.org/wiki/Tom_Hardy"],
          "descripcion": "Un ladrón roba secretos mediante la estructura de los sueños y debe implantar una idea.",
          "iframe": "https://www.youtube.com/embed/RV9L7ui9Cn8?si=n8bnCO7aCGvnx1pD",
          "portadaJPG": "https://a.ltrbxd.com/resized/sm/upload/sv/95/s9/4j/inception-0-1000-0-1500-crop.jpg?v=30d7224316",
          "rating": 8.8,
          "clasificacion": "+13",
          "estreno": 2010,
          "linkComenzar": "https://www.youtube.com/watch?v=RV9L7ui9Cn8"
        },
        {
          "titulo": "Se7en",
          "duracion": 127,
          "genero": "Crimen, misterio, thriller",
          "actores": ["Brad Pitt", "Morgan Freeman", "Gwyneth Paltrow"],
          "linkActores": ["https://es.wikipedia.org/wiki/", "https://es.wikipedia.org/wiki/", "https://es.wikipedia.org/wiki/", "https://es.wikipedia.org/wiki/"],
          "descripcion": "Dos detectives investigan a un asesino que usa los siete pecados capitales como motivo.",
          "iframe": "https://www.youtube.com/embed/xhzBmjdehPA?si=6NvVjtsOUM2OuFKG",
          "portadaJPG": "https://a.ltrbxd.com/resized/film-poster/5/1/3/4/5/51345-se7en-0-1000-0-1500-crop.jpg?v=76a14ef6b4",
          "rating": 8.6,
          "clasificacion": "+18",
          "estreno": 1995,
          "linkComenzar": ""
        },
        {
          "titulo": "Bastardos sin gloria",
          "duracion": 153,
          "genero": "Acción, guerra, drama",
          "actores": ["Brad Pitt", "Diane Kruger", "Eli Roth"],
          "linkActores": ["https://es.wikipedia.org/wiki/Brad_Pitt", "https://es.wikipedia.org/wiki/Diane_Kruger", "https://es.wikipedia.org/wiki/Eli_Roth"],
          "descripcion": "Durante la II Guerra Mundial, un grupo de soldados planea eliminar a líderes nazis.",
          "iframe": "https://www.youtube.com/embed/b8J_kP8Mses?si=J12d-940kKwctVY_",
          "portadaJPG": "https://a.ltrbxd.com/resized/film-poster/4/1/3/5/2/41352-inglourious-basterds-0-1000-0-1500-crop.jpg?v=0c74c673e0",
          "rating": 8.3,
          "clasificacion": "+18",
          "estreno": 2009,
          "linkComenzar": "https://www.youtube.com/watch?v=b8J_kP8Mses"
        },
        {
          "titulo": "Matrix",
          "duracion": 136,
          "genero": "Ciencia ficción, acción",
          "actores": ["Keanu Reeves", "Laurence Fishburne", "Carrie-Anne Moss"],
          "linkActores": ["https://es.wikipedia.org/wiki/Keanu_Reeves", "https://es.wikipedia.org/wiki/Laurence_Fishburne", "https://es.wikipedia.org/wiki/Carrie-Anne_Moss"],
          "descripcion": "Un hacker descubre que la realidad es una simulación y se une a la rebelión contra las máquinas.",
          "iframe": "https://www.youtube.com/embed/Pl_H2Lmjn6k?si=W75NAU4dbfudolwP",
          "portadaJPG": "https://a.ltrbxd.com/resized/film-poster/5/1/5/1/8/51518-the-matrix-0-1000-0-1500-crop.jpg?v=fc7c366afe",
          "rating": 8.7,
          "clasificacion": "+16",
          "estreno": 1999,
          "linkComenzar": "https://www.youtube.com/watch?v=Pl_H2Lmjn6k"
        },
        {
          "titulo": "Interstellar",
          "duracion": 169,
          "genero": "Ciencia ficción, aventura, drama",
          "actores": ["Matthew McConaughey", "Anne Hathaway", "Jessica Chastain", "Michael Caine"],
          "linkActores": ["https://es.wikipedia.org/wiki/Matthew_McConaughey", "https://es.wikipedia.org/wiki/Anne_Hathaway", "https://es.wikipedia.org/wiki/Jessica_Chastain", "https://es.wikipedia.org/wiki/Michael_Caine"],
          "descripcion": "Un grupo de exploradores viaja por un agujero de gusano en busca de un nuevo hogar para la humanidad.",
          "iframe": "https://www.youtube.com/embed/5mAbnQQiPD8?si=hh-_hqn7nx23TUqX",
          "portadaJPG": "https://a.ltrbxd.com/resized/film-poster/1/1/7/6/2/1/117621-interstellar-0-1000-0-1500-crop.jpg?v=7ad89e6666",
          "rating": 8.6,
          "clasificacion": "+13",
          "estreno": 2014,
          "linkComenzar": "https://www.youtube.com/watch?v=5mAbnQQiPD8"
        },
        {
          "titulo": "El resplandor",
          "duracion": 146,
          "genero": "Terror, misterio, drama",
          "actores": ["Jack Nicholson", "Shelley Duvall", "Scatman Crothers"],
          "linkActores": ["https://es.wikipedia.org/wiki/Jack_Nicholson", "https://es.wikipedia.org/wiki/Shelley_Duvall", "https://es.wikipedia.org/wiki/Scatman_Crothers"],
          "descripcion": "Un hombre enloquece en un hotel aislado durante el invierno, amenazando a su familia.",
          "iframe": "https://www.youtube.com/embed/IiSjPcRWjYA?si=C0ymSSNhx5Xx9LQ2",
          "portadaJPG": "https://a.ltrbxd.com/resized/sm/upload/7s/m2/bw/d0/caoYMcjUamGoBVy65i1AHJBvdzw-0-1000-0-1500-crop.jpg?v=88d9d6cce4",
          "rating": 8.4,
          "clasificacion": "+16",
          "estreno": 1980,
          "linkComenzar": "https://www.youtube.com/watch?v=IiSjPcRWjYA"
        },
        {
          "titulo": "El caballero de la noche",
          "duracion": 152,
          "genero": "Acción, crimen, drama",
          "actores": ["Christian Bale", "Heath Ledger", "Aaron Eckhart"],
          "linkActores": ["https://es.wikipedia.org/wiki/Christian_Bale", "https://es.wikipedia.org/wiki/Heath_Ledger", "https://es.wikipedia.org/wiki/Aaron_Eckhart"],
          "descripcion": "Batman se enfrenta a una ola de crimen desencadenada por el Balatro en Gotham.",
          "iframe": "https://www.youtube.com/embed/kj7urtvmwrY?si=hXcGo9O2aVuUnhl7",
          "portadaJPG": "https://a.ltrbxd.com/resized/sm/upload/78/y5/zg/ej/oefdD26aey8GPdx7Rm45PNncJdU-0-1000-0-1500-crop.jpg?v=2d0ce4be25",
          "rating": 9.0,
          "clasificacion": "+16",
          "estreno": 2008,
          "linkComenzar": "https://www.youtube.com/watch?v=kj7urtvmwrY"
        },
        {
          "titulo": "La sustancia",
          "duracion": 126,
          "genero": "Ciencia ficción, thriller",
          "actores": ["Emma Roberts", "Molly Ringwald", "Jennifer Jason Leigh"],
          "linkActores": ["https://es.wikipedia.org/wiki/Emma_Roberts", "https://es.wikipedia.org/wiki/Molly_Ringwald", "https://es.wikipedia.org/wiki/Jennifer_Jason_Leigh"],
          "descripcion": "Mientras una nueva droga se extiende, investigadores revelan oscuros secretos detrás de su fabricación.",
          "iframe": "https://www.youtube.com/embed/bb10YAiF8nE?si=dOcJjTbGd4QlrOFi",
          "portadaJPG": "https://a.ltrbxd.com/resized/film-poster/8/3/8/1/4/0/838140-the-substance-0-1000-0-1500-crop.jpg?v=ab9e1072f8",
          "rating": 5.2,
          "clasificacion": "+16",
          "estreno": 2020,
          "linkComenzar": "https://www.youtube.com/watch?v=bb10YAiF8nE"
        }
]
